"""URI lookup tables for the batch-annotator (`_annotate_all_configs.py`).

Three tables:

- `NAME_URIS` — attribute / association-role local-name → compact-prefix URI.
  Applies uniformly across every mapping config. Extracted by parsing the
  first-line hint ('skos:X - ...') from each element's definition text.
  Auto-generated by scripts/_propose_uris.py (2026-07-07).

- `CLASS_URIS` — CDIF target-class name → compact-prefix URI.
  Same rules as NAME_URIS but at class scope.

- `PROFILE_OVERRIDES` — per-profile overrides for the ~22 names that map to
  different URIs in different profiles (e.g. `has` role is
  `cdif:has_CategoryStatistics` in DataDescription but
  `cdi:has_DataStructureComponent` in DataStructure). Keyed on
  (profile_slug, local_name) → URI. Beats NAME_URIS when a match is found.

- `PENDING_REVIEW` — names for which the automated extraction found no hint.
  Left as an empty-URI list so a human decides whether each has a source
  vocabulary or is CDIF-native (no URI needed).

Compact prefix keys the augmenter resolves:
  schema:  → http://schema.org/
  skos:    → http://www.w3.org/2004/02/skos/core#
  dcterms: → http://purl.org/dc/terms/
  dcat:    → http://www.w3.org/ns/dcat#
  prov:    → http://www.w3.org/ns/prov#
  dqv:     → http://www.w3.org/ns/dqv#
  spdx:    → http://spdx.org/rdf/terms#
  time:    → http://www.w3.org/2006/time#
  geo:     → http://www.opengis.net/ont/geosparql#
  cdi:     → http://ddialliance.org/Specification/DDI-CDI/1.0/RDF/
  cdif:    → https://w3id.org/cdif/    (CDIF-modified cdi terms)

Names bound to `cdif:X` are CDIF-modified `cdi:X` terms — the augmenter
uses the source `cdi:X` property as the upstream source in the Original
section (Reference still shows the `cdif:X` URI so consumers see the
CDIF-specific namespace; Definition/Scope come from the DDI-CDI source).
"""

# Attribute / association-role local-name → compact URI.
# Auto-extracted from the definition-text prefix hints; 242 unambiguous entries.
NAME_URIS = {
    # ---- schema.org attributes ----
    "about":                 "schema:about",
    "additionalType":        "schema:additionalType",
    "affiliation":           "schema:affiliation",
    "alternateName":         "schema:alternateName",
    "box":                   "schema:box",
    "checksum":              "schema:checksum",
    "conditionsOfAccess":    "schema:conditionsOfAccess",
    "contactPoint":          "schema:contactPoint",
    "contentSize":           "schema:contentSize",
    "contentType":           "schema:contentType",
    "contentUrl":            "schema:contentUrl",
    "dateModified":          "schema:dateModified",
    "datePublished":         "schema:datePublished",
    "description":           "schema:description",
    "documentation":         "schema:documentation",
    "email":                 "schema:email",
    "encodingFormat":        "schema:encodingFormat",
    "familyName":            "schema:familyName",
    "givenName":             "schema:givenName",
    "honorificPrefix":       "schema:honorificPrefix",
    "identifier":            "schema:identifier",
    "keywords":              "schema:keywords",
    "license":               "schema:license",
    "location":              "schema:location",
    "manufacturer":          "schema:manufacturer",
    "measurementTechnique":  "schema:measurementTechnique",
    "minValue":              "schema:minValue",
    "maxValue":              "schema:maxValue",
    "model":                 "schema:model",
    "name":                  "schema:name",
    "owner":                 "schema:owner",
    "propertyId":            "schema:propertyID",
    "sdDatePublished":       "schema:sdDatePublished",
    "size":                  "schema:size",
    "startTime":             "schema:startTime",
    "endTime":               "schema:endTime",
    "startDate":             "schema:startDate",
    "endDate":               "schema:endDate",
    "unitCode":              "schema:unitCode",
    "unitText":              "schema:unitText",
    "url":                   "schema:url",
    "validFrom":             "schema:validFrom",
    "validThrough":          "schema:validThrough",
    "value":                 "schema:value",
    "version":               "schema:version",
    # 2026-07-08 batch: names that surfaced un-annotated after first pass.
    "sameAs":                "schema:sameAs",
    "inLanguage":            "schema:inLanguage",
    "publishingPrinciples":  "schema:publishingPrinciples",
    "relatedLink":           "schema:relatedLink",
    "termsOfService":        "schema:termsOfService",
    "serviceType":           "schema:serviceType",
    "httpMethod":            "schema:httpMethod",
    "valueName":             "schema:valueName",
    "valueRequired":         "schema:valueRequired",
    "valuePattern":          "schema:valuePattern",
    "roleName":              "schema:roleName",
    "termCode":              "schema:termCode",
    "inDefinedTermSet":      "schema:inDefinedTermSet",
    "propertyID":            "schema:propertyID",   # canonical spelling (Id variant kept above)
    "includedInDataCatalog": "schema:includedInDataCatalog",
    "line":                  "schema:line",
    "subjectOf":             "schema:subjectOf",   # cleared 8+ profile-independent associations
    "variableMeasured":      "schema:variableMeasured",
    "hasPart":               "schema:hasPart",
    "participant":           "schema:participant", # NB: schema:participant, not prov:participant
    # DCTerms
    "relation":              "dcterms:relation",
    # PROV
    "used":                  "prov:used",
    # OWL-Time
    "numericPosition":       "time:numericPosition",
    "hasTRS":                "time:hasTRS",
    # DDI-CDI plain form (target-qualified variants live in PROFILE_OVERRIDES).
    "isDefinedBy":           "cdi:isDefinedBy",
    # CDIF-invented union carrier for the DataDownload/ArchivePart alsoTypedAs pattern.
    "alsoTypedAs":           "cdif:alsoTypedAs",

    # ---- SKOS ----
    "prefLabel":             "skos:prefLabel",
    "altLabel":              "skos:altLabel",
    "note":                  "skos:note",
    "notation":              "skos:notation",
    "hasTopConcept":         "skos:hasTopConcept",
    "broader":               "skos:broader",
    "narrower":              "skos:narrower",
    "inScheme":              "skos:inScheme",
    "topConceptOf":          "skos:topConceptOf",
    "publisher":             "schema:publisher",
    "creator":               "schema:creator",
    "provider":              "schema:provider",
    "contributor":           "schema:contributor",
    "maintainer":            "schema:maintainer",
    "funder":                "schema:funder",
    "funding":               "schema:funding",
    "distribution":          "schema:distribution",  # schema:distribution used, not dcat:distribution
    "spatialCoverage":       "schema:spatialCoverage",
    "temporalCoverage":      "schema:temporalCoverage",    
    # ---- DCTerms / DCMI ----
    "conformsTo":            "dcterms:conformsTo",


    # ---- PROV-O ----
    "wasDerivedFrom":        "prov:wasDerivedFrom",
    "wasGeneratedBy":        "prov:wasGeneratedBy",

    # ---- DQV ----
    "isMeasurementOf":       "dqv:isMeasurementOf",
    "hasQualityMeasurement": "dqv:hasQualityMeasurement",

    # ---- OWL-Time ----
    "hasBeginning":          "time:hasBeginning",
    "hasEnd":                "time:hasEnd",
    "inTimePosition":        "time:inTimePosition",
    "intervalStartedBy":     "time:intervalStartedBy",
    "intervalFinishedBy":    "time:intervalFinishedBy",

    # ---- schema.org geo / geosparql ----
    "geo":                   "schema:geo",
    "latitude":              "schema:latitude",
    "longitude":             "schema:longitude",

    # ---- DDI-CDI attributes / associations ----
    "actionProcess":         "schema:actionProcess",
    "actionStatus":          "schema:actionStatus",
    # DataFingerprint attributes use the class-qualified URI form
    # (`cdi:<Class>-<attr>`) because the DDI-CDI lookup keys attributes under
    # their owning class in the canonical XMI. Bare `cdi:algorithmSpecification`
    # would not resolve. `typeOfFingerprint` follows the same pattern.
    "algorithmSpecification":"cdi:DataFingerprint-algorithmSpecification",
    "algorithmVersion":      "cdi:DataFingerprint-algorithmVersion",
    "typeOfFingerprint":     "cdi:DataFingerprint-typeOfFingerprint",
    "arrayBase":             "cdi:arrayBase",
    "characterSet":          "cdi:characterSet",
    "classificationLevel":   "cdi:classificationLevel",
    "commentPrefix":         "cdi:commentPrefix",
    "computationBase":       "cdi:computationBase",
    "content":               "cdi:content",
    "decimalPositions":      "cdi:decimalPositions",
    "defaultDecimalSeparator":"cdi:defaultDecimalSeparator",
    "defaultDigitGroupSeparator":"cdi:defaultDigitGroupSeparator",
    "defaultValue":          "cdi:defaultValue",
    "describedUnitOfMeasure":"cdi:describedUnitOfMeasure",
    "fingerprint":           "cdi:fingerprint",
    "function":              "cdi:function",
    "hasIntendedDataType":   "cdi:hasIntendedDataType",
    "hasWeight":             "cdi:hasWeight",             # sometimes cdif:hasWeight — verify
    "indexes":               "cdi:indexes",
    "isBoundedBy":           "cdi:isBoundedBy",
    "isComposedOf":          "cdi:isComposedOf",
    "isDescribedBy":         "cdi:isDescribedBy",
    "isStructuredBy":        "cdi:isStructuredBy",
    "isWeighted":            "cdi:isWeighted",
    "logicalExpression":     "cdi:logicalExpression",
    "maximumValueExclusive": "cdi:maximumValueExclusive",
    "maximumValueInclusive": "cdi:maximumValueInclusive",
    "measures":              "cdi:measures",
    "minimumValueExclusive": "cdi:minimumValueExclusive",
    "minimumValueInclusive": "cdi:minimumValueInclusive",
    "numberPattern":         "cdi:numberPattern",
    "physicalDataType":      "cdi:physicalDataType",
    "platformType":          "cdi:platformType",
    "purpose":               "cdi:purpose",
    "qualifies":             "cdi:qualifies",
    "refersTo":              "cdi:refersTo",
    "regularExpression":     "cdi:regularExpression",
    "role":                  "cdi:role",
    "scale":                 "cdi:scale",
    "source":                "cdi:source",
    "takesSentinelValuesFrom":   "cdi:takesSentinelValuesFrom",
    "takesSubstantiveValuesFrom":"cdi:takesSubstantiveValuesFrom",
    "textFormat":            "cdi:textFormat",
    "typeOfNumericValue":    "cdi:typeOfNumericValue",
    "typeOfStatistic":       "cdi:typeOfStatistic",
    "url":                   "schema:url",

    # ---- schema.org action-family ----
    "potentialAction":       "schema:potentialAction",
    "queryInput":            "schema:query-input",
    "target":                "schema:target",
    "result":                "schema:result",
    "urlTemplate":           "schema:urlTemplate",
    "encodingType":          "schema:encodingType",
    "contentType":           "schema:contentType",

    # ---- CDIF-specific (no upstream) ----
    "appliesTo":             "cdif:appliesTo",
    "definition":            "skos:definition",   # NOTE: cdifDataDescription uses cdif:definition — see PROFILE_OVERRIDES
    "descriptiveText":       "cdif:descriptiveText",
    "displayLabel":          "cdif:displayLabel",
    "for":                   "cdif:for",
    "formats_InstanceVariable":"cdif:formats_InstanceVariable",
    "hasPhysicalMapping":    "cdif:hasPhysicalMapping",
    "hasValuesFrom":         "cdif:hasValuesFrom",
    "indexedBy":             "cdif:indexedBy",
    "isDescribedBy_StatisticsCollection":"cdif:isDescribedBy_StatisticsCollection",
    "position":              "cdif:position",
    "recommendedDataType":   "cdif:recommendedDataType",
    "references":            "cdif:references",     # NOTE: cdi:references in DataStructure — see PROFILE_OVERRIDES
    "simpleUnitOfMeasure":   "cdif:simpleUnitOfMeasure",
    "statistics":            "cdif:statistics",
    "subUnitAmount":         "cdif:subUnitAmount",
    "takesValuesFrom":       "cdif:takesValuesFrom",
    "uses":                  "cdif:uses",           # NOTE: prov:used in Provenance — see PROFILE_OVERRIDES
}


CLASS_URIS = {
    # schema.org
    # Every CDIF class here is a restriction/refinement of the schema.org term.
    # sourceUri points to the upstream schema.org URI so the Original section
    # of the emitted ownedComment reads from schema.org's canonical definition.
    "Dataset":              "schema:Dataset",           # CDIF Core Dataset is a restriction of schema:Dataset (also aligns with cdi:Dataset)
    "Person":               "schema:Person",            # CDIF Core Person is a restriction of schema:Person
    "Organization":         "schema:Organization",      # CDIF Core Organization is a restriction of schema:Organization
    "DefinedTerm":          "schema:DefinedTerm",       # CDIF Core DefinedTerm is a restriction of schema:DefinedTerm
    "PropertyValue":        "schema:PropertyValue",
    "Identifier":           "schema:PropertyValue",     # CDIF Identifier is schema:PropertyValue
    "VariableMeasured":     "schema:PropertyValue",     # CDIF Discovery VariableMeasured has datatype schema:PropertyValue — restriction of schema:PropertyValue
    "Contributor":          "schema:Person",            # or Organization; ambiguous
    "ContactPoint":         "schema:ContactPoint",      # CDIF Core ContactPoint extends schema:ContactPoint
    "MonetaryGrant":        "schema:MonetaryGrant",
    "QuantitativeValue":    "schema:QuantitativeValue", # CDIF Manifest QuantitativeValue implements schema:QuantitativeValue
    "Action":               "schema:Action",
    "EntryPoint":           "schema:EntryPoint",
    "ActionResult":         "schema:Thing",             # verify
    "PropertyValueSpecification": "schema:PropertyValueSpecification",
    "WebAPI":               "schema:WebAPI",
    "DataDownload":         "schema:DataDownload",      # CDIF Core DataDownload is a refinement of schema:DataDownload
    "Instrument":           "schema:Thing",             # verify — likely schema.org's Instrument
    "AgentInRole":          "schema:Role",

    # SKOS
    "ConceptScheme":        "skos:ConceptScheme",
    "Concept":              "skos:Concept",

    # DCAT
    "CatalogRecord":        "dcat:CatalogRecord",

    # PROV-O
    # cdifCore ProvActivity is a restriction of prov:Activity (to a simple string
    # or object reference at CDIF Core; the fuller shape is in cdifProvenance).
    "ProvActivity":         "prov:Activity",
    "Activity":             "prov:Activity",

    # DQV
    "QualityMeasure":       "dqv:QualityMeasure",
    "QualityMeasurement":   "dqv:QualityMeasurement",

    # OWL-Time
    "TemporalExtent":       "time:ProperInterval",
    "Instant":              "time:Instant",
    "TimePosition":         "time:TimePosition",

    # GeoSPARQL
    "SpatialExtent":        "schema:Place",             # not exactly geo — verify
    "Geometry":             "geo:Geometry",
    "AbstractGeometry":     "geo:Geometry",
    "GeoCoordinates":       "schema:GeoCoordinates",
    "GeoShape":             "schema:GeoShape",

    # SPDX (Software Package Data Exchange), for archive/manifest checksums
    "Checksum":             "spdx:Checksum",            # CDIF Manifest Checksum is spdx:Checksum

    # DDI-CDI
    # cdifDataDescription InstanceVariable is a restriction of cdi:InstanceVariable
    # (fattened at DataDescription level with physicalDataType etc.).
    "InstanceVariable":     "cdi:InstanceVariable",
    # cdifCore Agent is a restriction of cdi:Agent (abstract parent of Person/Organization).
    "Agent":                "cdi:Agent",
    # cdifDataStructure DimensionGroup is a restriction of cdi:DimensionGroup.
    "DimensionGroup":       "cdi:DimensionGroup",
    "RepresentedVariable":  "cdi:RepresentedVariable",
    "DescriptorVariable":   "cdi:DescriptorVariable",
    "AbstractVariable":     "cdi:AbstractVariable",
    "DataStructure":        "cdi:DataStructure",
    "DimensionalDataStructure": "cdi:DimensionalDataStructure",
    "LongDataStructure":    "cdi:LongDataStructure",
    "WideDataStructure":    "cdi:WideDataStructure",
    "DataStructureComponent":"cdi:DataStructureComponent",
    "IdentifierComponent":  "cdi:IdentifierComponent",
    "MeasureComponent":     "cdi:MeasureComponent",
    "AttributeComponent":   "cdi:AttributeComponent",
    "DimensionComponent":   "cdi:DimensionComponent",
    "VariableValueComponent":"cdi:VariableValueComponent",
    "VariableDescriptorComponent":"cdi:VariableDescriptorComponent",
    "PrimaryKey":           "cdi:PrimaryKey",
    "PrimaryKeyComponent":  "cdi:PrimaryKeyComponent",
    "ForeignKey":           "cdi:ForeignKey",
    "ForeignKeyComponent":  "cdi:ForeignKeyComponent",
    "ComponentPosition":    "cdi:ComponentPosition",
    "PhysicalDataSet":      "cdi:PhysicalDataSet",
    "TabularTextDataSet":   "cdi:TabularTextDataSet",
    "StructuredDataSet":    "cdi:StructuredDataSet",
    "PhysicalMapping":      "cdi:PhysicalMapping",
    "TextMapping":          "cdi:TextMapping",
    "LocatorMapping":       "cdi:LocatorMapping",
    "AbstractMapping":      "cdi:AbstractMapping",
    "AbstractDataSet":      "cdi:AbstractDataSet",
    "Statistic":            "cdi:Statistic",
    "Statistics":           "cdi:Statistics",
    "CategoryStatistics":   "cdi:CategoryStatistics",
    "StatisticsCollection": "cdi:StatisticsCollection",
    "Category":             "cdi:Category",
    "SubstantiveValueDomain":"cdi:SubstantiveValueDomain",
    "SentinelValueDomain":  "cdi:SentinelValueDomain",
    "DescriptorValueDomain":"cdi:DescriptorValueDomain",
    "EnumerationDomain":    "cdi:EnumerationDomain",
    "ValueAndConceptDescription":"cdi:ValueAndConceptDescription",
    "UnitType":             "cdi:UnitType",
    "ArchivePart":          "cdi:ArchivePart",
    "DataFingerprint":      "cdi:DataFingerprint",

    # CDIF-native (no upstream)
    "CdifConceptOrTerm":            None,   # CDIF-only union DataType
    "CdifConceptOrTermOrString":    None,   # CDIF-only union DataType
    "AbstractDistribution":         None,   # CDIF-only abstract supertype
    "AdditionalProperty":           "schema:PropertyValue",
    "DerivedFrom":                  "prov:wasDerivedFrom",  # verify
    "Reference":                    None,   # CDIF-native @id-plus-metadata shorthand
}


# Per-(profile, name) or per-(profile, class, attr) overrides where the
# generic NAME_URIS entry is wrong. Wins over NAME_URIS. Two key shapes are
# accepted:
#
#   (profile_slug, local_name)        — 2-tuple: applies to every class
#                                       in the profile that uses this name.
#   (profile_slug, class_name, attr)  — 3-tuple: only applies when the
#                                       attribute sits on the named target
#                                       class. Wins over the 2-tuple form
#                                       for the same (profile, name).
#
# The 3-tuple form disambiguates cases where a local name maps to different
# URIs on different classes in the same profile — e.g. `value` is
# `cdi:DataFingerprint-value` on DataFingerprint but `schema:value` on the
# schema:PropertyValue-shaped Identifier.
#
# Lookup order (best-match wins): 3-tuple → 2-tuple → NAME_URIS.
#
# NAMESPACE POLICY (per Stephen's 2026-07-07 review):
#   - `cdi:X` = property used as-is from DDI-CDI (unchanged range, no CDIF restrictions).
#   - `cdif:X` = property with CDIF-modified value range OR CDIF-added restrictions,
#     OR a CDIF-invented property with no DDI-CDI counterpart.
PROFILE_OVERRIDES = {
    # ---- cdifDataStructure ----
    # DataStructureComponent split: DDI-CDI's polymorphic cdi:has typed to concrete
    # subclasses. Per Stephen: all 12 use cdi:has_DataStructureComponent (the range
    # narrowing is not a CDIF-invented restriction; it's just the diagram splitting
    # the polymorphic parent for visualization). The one DimensionGroup case
    # currently marked cdif: in the config needs to be changed to cdi: — see
    # CONFIG_EDITS_NEEDED below.
    ("cdifDataStructure",  "has"):          "cdi:has_DataStructureComponent",
    ("cdifDataStructure",  "hasComponent"): "cdi:has_DataStructureComponent",
    ("cdifDataStructure",  "hasPrimaryKey"):"cdi:has_PrimaryKey",
    ("cdifDataStructure",  "hasForeignKey"):"cdi:has_ForeignKey",
    # ForeignKey_isComposedOf_RepresentedVariable: per Stephen, this is a CDIF
    # flattening of DDI-CDI's ForeignKey.isComposedOf → ForeignKeyComponent.
    # Value range changed from ForeignKeyComponent to RepresentedVariable → cdif:.
    ("cdifDataStructure",  "isComposedOf"): "cdif:isComposedOf",
    ("cdifDataStructure",  "references"):  "cdi:references",
    ("cdifDataStructure",  "isDefinedBy_RepresentedVariable"):"cdif:isDefinedBy_RepresentedVariable",
    ("cdifDataStructure",  "isDefinedBy_DescriptorVariable"): "cdif:isDefinedBy_DescriptorVariable",

    # ---- cdifDataDescription ----
    ("cdifDataDescription","has_CategoryStatistics"):"cdif:has_CategoryStatistics",
    # Per Stephen: rename this assoc to match DDI-CDI. Target association name
    # StatisticsCollection_isComposedOf_Statistics changes to
    # StatisticsCollection_has_Statistics AND the URI becomes cdi:has_Statistics.
    # See CONFIG_EDITS_NEEDED below.
    ("cdifDataDescription","has_Statistics"):        "cdi:has_Statistics",
    ("cdifDataDescription","definition"):            "cdif:definition",
    ("cdifDataDescription","references"):            "cdif:references",
    ("cdifDataDescription","hasWeight"):             "cdif:hasWeight",
    ("cdifDataDescription","isDescribedBy_StatisticsCollection"):"cdif:isDescribedBy_StatisticsCollection",
    ("cdifDataDescription","hasPrimaryKey"):         "cdif:hasPrimaryKey",

    # ---- cdifProvenance ----
    ("cdifProvenance",     "uses"):                  "prov:used",  # NB: role name "uses" maps to prov:used, not prov:uses
    ("cdifProvenance",     "agent"):                 "prov:wasAssociatedWith",  # verify

    # ---- cdifCore ----
    ("cdifCore",           "queryInput"):            "schema:query-input",
    # WebAPI.potentialActionResult -> ActionResult reifies the schema:potentialAction
    # target as its result. The upstream property is schema:result. Keyed on the
    # target-qualified role form because the parser tries that first.
    ("cdifCore",           "potentialActionResult_ActionResult"): "schema:result",
    ("cdifDataDescription","potentialActionResult_ActionResult"): "schema:result",

    # ---- Class-scoped overrides (3-tuple form) ----
    # `value` on DataFingerprint pulls from the DDI-CDI DataFingerprint class
    # attribute rather than the more common schema:value. DataDescription and
    # Manifest both restate the DataFingerprint DataType.
    ("cdifDataDescription", "DataFingerprint", "value"): "cdi:DataFingerprint-value",
    ("cdifManifest",        "DataFingerprint", "value"): "cdi:DataFingerprint-value",
}


# Class-scoped DDI-CDI attributes. When an attribute with name `attr` sits on a
# CDIF class of the same name as a DDI-CDI class in this table, resolve_uri()
# returns `cdi:<Class>-<attr>` — the class-qualified form used in the DDI-CDI
# canonical XMI. Profile-agnostic on purpose: these attributes come from the
# same DDI-CDI classes wherever they appear (DataDescription, Manifest, etc.).
# Consulted AFTER PROFILE_OVERRIDES and NAME_URIS so per-profile overrides
# still win.
CDI_CLASS_ATTRS = {
    "ValueAndConceptDescription": {"formatPattern", "isRequired", "externalDefinition"},
    "PhysicalMapping": {"index", "format", "length", "maximumLength", "minimumLength",
                        "nullSequence", "isRequired"},
    "TextMapping":    {"index", "isFixedWidth", "length"},
    "LocatorMapping": {"locator"},
    "TabularTextDataSet": {"isDelimited", "isFixedWidth", "hasHeader", "headerRowCount",
                           "headerIsCaseSensitive", "lineTerminator", "quoteCharacter",
                           "escapeCharacter", "skipBlankRows", "skipDataColumns",
                           "skipInitialSpace", "skipRows", "treatConsecutiveDelimitersAsOne",
                           "trim", "tableDirection", "textDirection"},
}


def resolve_uri(profile: str, class_name: str, attr_name: str) -> str:
    """Return the best-matching source URI for a given (profile, class, attr).

    Lookup order (first hit wins):
      1. 3-tuple: PROFILE_OVERRIDES[(profile, class_name, attr_name)]
      2. 2-tuple: PROFILE_OVERRIDES[(profile, attr_name)]
      3. Flat NAME_URIS[attr_name]
      4. PENDING_REVIEW[attr_name]
      5. CDI_CLASS_ATTRS[class_name] contains attr_name → `cdi:<Class>-<attr>`
      6. Empty string (leave the sourceUri field blank).

    The batch annotator (`_annotate_all_configs.py`) uses this to write the
    `sourceUri:` field into each mapping-config element."""
    triple = PROFILE_OVERRIDES.get((profile, class_name, attr_name))
    if triple:
        return triple
    pair = PROFILE_OVERRIDES.get((profile, attr_name))
    if pair:
        return pair
    if attr_name in NAME_URIS:
        return NAME_URIS[attr_name]
    if attr_name in PENDING_REVIEW:
        return PENDING_REVIEW[attr_name]
    if attr_name in CDI_CLASS_ATTRS.get(class_name, ()):
        return f"cdi:{class_name}-{attr_name}"
    return ""


def resolve_class_uri(class_name: str) -> str:
    """Return the CLASS_URIS entry for a target class, or empty string if
    none. `None` values (CDIF-invented classes with no upstream source) are
    returned as-is so callers can distinguish "explicit no-source" from
    "unknown"."""
    val = CLASS_URIS.get(class_name)
    return val if val is not None else ""


# Structural config edits required to align with the namespace policy above.
# (These are edits to the mapping-config .json files themselves — the URI
# lookup can't fix them; the definitions/targetAssociationNames need updates.)
CONFIG_EDITS_NEEDED = [
    # 1. cdifDataStructure: DimensionGroup_hasComponent_* — 4 assocs currently say
    #    "cdif:has_DataStructureComponent" in their definition text. Change the
    #    definition prefix to "cdi:has_DataStructureComponent" to align with the
    #    other 8 hasComponent entries in the same config.
    (
        "configuration/ddi-cdi2cdifDataStructure_mapping.json",
        [
            "DimensionGroup_hasComponent_AttributeComponent",
            "DimensionGroup_hasComponent_DimensionComponent",
            "DimensionGroup_hasComponent_IdentifierComponent",
            "DimensionGroup_hasComponent_MeasureComponent",
        ],
        "definition prefix: cdif:has_DataStructureComponent → cdi:has_DataStructureComponent",
    ),
    # 2. cdifDataStructure: ForeignKey_isComposedOf_RepresentedVariable —
    #    definition currently says "cdi:isComposedOf". Change to "cdif:isComposedOf"
    #    because CDIF flattens ForeignKeyComponent → RepresentedVariable (range change).
    (
        "configuration/ddi-cdi2cdifDataStructure_mapping.json",
        ["ForeignKey_isComposedOf_RepresentedVariable"],
        "definition prefix: cdi:isComposedOf → cdif:isComposedOf",
    ),
    # 3. cdifDataDescription: StatisticsCollection_isComposedOf_Statistics — rename
    #    to StatisticsCollection_has_Statistics AND change definition prefix from
    #    "cdif:isComposedOf" to "cdi:has_Statistics" (align with DDI-CDI naming).
    (
        "configuration/ddi-cdi2cdifDataDescription_mapping.json",
        ["StatisticsCollection_isComposedOf_Statistics"],
        "RENAME to StatisticsCollection_has_Statistics; definition prefix cdif:isComposedOf → cdi:has_Statistics",
    ),
]


# Names for which the automated extraction found no hint. Fill in with the
# correct URI (or leave "" if the term is CDIF-native and has no upstream
# source). The annotator skips entries with empty URIs.
PENDING_REVIEW = {
    # ---- Manifest checksum machinery (SPDX 2.3, ns http://spdx.org/rdf/terms#) ----
    "checksum":              "spdx:checksum",       # ASSOC in Manifest
    "checksumValue":         "spdx:checksumValue",
    "checksumAlgorithm":     "spdx:algorithm",
    "algorithm":             "spdx:algorithm",      # also used in DataDescription

    # ---- Manifest / DataDescription tabular / text machinery ----
    # Stephen's policy: use cdi: properties for equivalent csvw properties.
    "delimiter":             "cdi:TabularTextDataSet-delimiter",  # DDI-CDI has this attribute; use cdi in preference to csvw:delimiter
    # `encoding` is based on schema.org encoding.
    "encoding":              "schema:encoding",
    # countColumns / countRows are CDIF-invented (not in DDI-CDI, not in csvw).
    "countColumns":          "cdif:countColumns",
    "countRows":             "cdif:countRows",

    # ---- GeoSPARQL ----
    "hasGeometry":           "geosparql:hasGeometry",
    "asWKT":                 "geosparql:asWKT",
    # GeoSPARQL 1.1 doesn't have a distinct `crs` property (CRS is embedded in
    # the WKT string via the URN prefix). CDIF-invented convenience attribute.
    "crs":                   "cdif:crs",

    # ---- Manifest structural / metadata ----
    "hadRole":               "dcat:hadRole",
    "error":                 "schema:error",

    # ---- Provenance temporal ----
    "startedAtTime":         "prov:startedAtTime",
    "endedAtTime":           "prov:endedAtTime",
    # `isPartOf` was flagged as pending earlier but is not used in any current
    # config; removed from the review list.
}
